source "https://rubygems.org"

ruby "3.3.5"
gem "activerecord", "~> 5.2"
gem "fiddle"
gem "logger"
gem "ostruct"
gem "pry"
gem "rake"
gem "require_all"
gem "sinatra-activerecord"
gem "sqlite3"

gem "rubocop"
gem "rubocop-rake", "~> 0.7.1"
